apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    user: mwalimu
    database: mwalimukit
    jsonData:
      sslmode: disable
      postgresVersion: "1600"
      timescaledb: false
